#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x235AE5F129F9ED98 (paul.l.kehrer@gmail.com)
#
Name     : pyOpenSSL
Version  : 17.5.0
Release  : 49
URL      : https://pypi.debian.net/pyOpenSSL/pyOpenSSL-17.5.0.tar.gz
Source0  : https://pypi.debian.net/pyOpenSSL/pyOpenSSL-17.5.0.tar.gz
Source99 : https://pypi.debian.net/pyOpenSSL/pyOpenSSL-17.5.0.tar.gz.asc
Summary  : Python wrapper module around the OpenSSL library
Group    : Development/Tools
License  : Apache-2.0
Requires: pyOpenSSL-python3
Requires: pyOpenSSL-python
Requires: cryptography
Requires: six
Requires: sphinx_rtd_theme
BuildRequires : cffi
BuildRequires : cffi-legacypython
BuildRequires : cffi-python
BuildRequires : cryptography
BuildRequires : cryptography-legacypython
BuildRequires : enum34
BuildRequires : enum34-legacypython
BuildRequires : idna-python
BuildRequires : ipaddress-legacypython
BuildRequires : ipaddress-python
BuildRequires : openssl-dev
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pyasn1
BuildRequires : pyasn1-legacypython
BuildRequires : pycparser
BuildRequires : pycparser-legacypython
BuildRequires : pycparser-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : setuptools-legacypython
BuildRequires : six
BuildRequires : tox
BuildRequires : virtualenv

%description
pyOpenSSL -- A Python wrapper around the OpenSSL library
        ========================================================

%package python
Summary: python components for the pyOpenSSL package.
Group: Default
Requires: pyOpenSSL-python3
Provides: pyopenssl-python

%description python
python components for the pyOpenSSL package.


%package python3
Summary: python3 components for the pyOpenSSL package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pyOpenSSL package.


%prep
%setup -q -n pyOpenSSL-17.5.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1523298289
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
